import { IDictionary } from "common-types";
import { IAwsLogConfig } from "./types";
export declare const logLevelLookup: IDictionary<number>;
export declare let config: IAwsLogConfig;
export declare function logger(requestedConfig?: Partial<IAwsLogConfig>): {
    context: typeof import("./logger").setContext;
    lambda: typeof import("./logger").lambda;
    reloadContext: typeof import("./logger").restoreState;
    log: typeof import("./logger").info;
    debug: typeof import("./logger").debug;
    info: typeof import("./logger").info;
    warn: typeof import("./logger").warn;
    error: typeof import("./logger").error;
    addToLocalContext: typeof import("./logger").addToLocalCtx;
    addToMaskedValues: (...props: (string | [string, import("./logger").IAwsLogMaskingStrategy])[]) => {
        log: typeof import("./logger").info;
        debug: typeof import("./logger").debug;
        info: typeof import("./logger").info;
        warn: typeof import("./logger").warn;
        error: typeof import("./logger").error;
        addToLocalContext: typeof import("./logger").addToLocalCtx;
        addToMaskedValues: any;
        setMaskedValues: (...props: (string | [string, import("./logger").IAwsLogMaskingStrategy])[]) => any;
        pathBasedMaskingStrategy: (strategy: import("./logger").IAwsLogMaskingStrategy, ...paths: string[]) => void;
        setStrategyForValue: (value: string, strategy: import("./logger").IAwsLogMaskingStrategy) => void;
        getContext: () => import("./types").IAwsLogContext;
        getCorrelationId: typeof import("./logger").getCorrelationId;
    };
    setMaskedValues: (...props: (string | [string, import("./logger").IAwsLogMaskingStrategy])[]) => {
        log: typeof import("./logger").info;
        debug: typeof import("./logger").debug;
        info: typeof import("./logger").info;
        warn: typeof import("./logger").warn;
        error: typeof import("./logger").error;
        addToLocalContext: typeof import("./logger").addToLocalCtx;
        addToMaskedValues: (...props: (string | [string, import("./logger").IAwsLogMaskingStrategy])[]) => any;
        setMaskedValues: any;
        pathBasedMaskingStrategy: (strategy: import("./logger").IAwsLogMaskingStrategy, ...paths: string[]) => void;
        setStrategyForValue: (value: string, strategy: import("./logger").IAwsLogMaskingStrategy) => void;
        getContext: () => import("./types").IAwsLogContext;
        getCorrelationId: typeof import("./logger").getCorrelationId;
    };
    pathBasedMaskingStrategy: (strategy: import("./logger").IAwsLogMaskingStrategy, ...paths: string[]) => void;
    setStrategyForValue: (value: string, strategy: import("./logger").IAwsLogMaskingStrategy) => void;
    getContext: () => import("./types").IAwsLogContext;
    getCorrelationId: typeof import("./logger").getCorrelationId;
};
